name: Deploy Github pages
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: redkubes/docusaurus-deploy-action@v1
        with:
          git-user: $SOME_USERNAME
          git-password: ${{ secrets.ACCESS_TOKEN }}
          deployment-branch: gh-pages